# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "google" {
        project = "pol-hsi-dev-001"
        region = "europe-west3"
    }
    provider "google-beta" {
        project = "pol-hsi-dev-001"
        region = "europe-west3"
    }
